'use strict';
const COPY={
'zh-Hans':{home:'首页',library:'术语库',practice:'练习',about:'项目介绍',badge:'教师演示 · 多语言学习',headline:'理解专业术语，<br>从你的语言开始。',intro:'把课堂里的英文概念，变成你能理解、记住和运用的知识。为不同母语的学习者设计。',start:'开始体验',explore:'浏览术语',sample:'示例学习卡',meaning:'母语释义',context:'课堂语境',remember:'从理解到记忆',courses:'课程主题',terms:'示例术语',languages:'学习语言',choose:'从一门课程开始',chooseSub:'传播与新媒体领域的精选示例词库。',open:'探索课程 →',workflow:'从课件，到你的词库',workflowSub:'产品方向：整理课件术语、核对释义，再按课程练习。此演示使用预先整理的示例，不上传文件、不调用 AI。',steps:['整理术语','理解概念','练习巩固'],demo:'独立演示站：使用 32 条示例术语；收藏和练习记录仅保存在此浏览器，不影响正式站词库。',libraryTitle:'让概念更容易理解。',librarySub:'英文术语保持原文，释义跟随你选择的语言。',search:'搜索英文术语或释义…',all:'全部课程',savedOnly:'仅看收藏',allWords:'全部术语',save:'收藏术语',unsave:'取消收藏',empty:'没有找到术语。试试其他关键词或课程。',found:'条术语',quizTitle:'把理解，变成记忆。',quizSub:'选出英文术语对应的释义。每轮 8 题，完成后查看成绩。',begin:'开始 8 题练习',back:'返回上一页',question:'题',select:'选择正确的释义',right:'答对了',wrong:'再看一下这个概念',next:'下一题',finish:'查看成绩',complete:'本轮练习完成',score:'答对',again:'再练一轮',review:'浏览术语复习',quizNote:'释义和选项随语言切换；题目与作答进度保留。',aboutTitle:'帮助不同母语的学生，读懂同一堂课。',aboutIntro:'CourseLex AI 是一个围绕大学课程的专业术语学习项目。它把英文术语与学习者熟悉的语言连接起来，再通过练习巩固理解。',problem:'我们想解决的问题',problemText:'学生可能认识一个词的日常用法，却不理解它在传播、政策或研究中的专业含义。查词、整理和复习分散在不同工具里，也让学习更费力。',experience:'你现在可以体验',features:['按四个课程主题浏览术语，搜索和收藏学习卡。','在简体中文、繁体中文、韩语和日语之间切换。','完成四选一练习，获得即时反馈并查看本轮成绩。'],nextTitle:'下一步，一起完善',nextText:'希望与老师及学生合作，验证课程术语的准确性、改进多语言释义，并测试练习是否帮助理解。正式产品已有课件整理方向；此站仅展示独立的学习体验。',attribution:'制作 @王大葱',version:'教师演示 · 版本 1.0',local:'本地收藏',total:'已完成练习',rounds:'轮',footer:'面向不同母语的学习者',courseNames:['新媒体政策与法规','传播学基础','互联网传播','传播与新媒体研究方法']},
'zh-Hant':{home:'首頁',library:'術語庫',practice:'練習',about:'專案介紹',badge:'教師展示 · 多語言學習',headline:'理解專業術語，<br>從你的語言開始。',intro:'把課堂裡的英文概念，變成你能理解、記住和運用的知識。為不同母語的學習者設計。',start:'開始體驗',explore:'瀏覽術語',sample:'示例學習卡',meaning:'母語釋義',context:'課堂語境',remember:'從理解到記憶',courses:'課程主題',terms:'示例術語',languages:'學習語言',choose:'從一門課程開始',chooseSub:'傳播與新媒體領域的精選示例詞庫。',open:'探索課程 →',workflow:'從課件，到你的詞庫',workflowSub:'產品方向：整理課件術語、核對釋義，再按課程練習。此展示使用預先整理的示例，不上傳檔案、不呼叫 AI。',steps:['整理術語','理解概念','練習鞏固'],demo:'獨立展示站：使用 32 條示例術語；收藏和練習紀錄僅儲存在此瀏覽器，不影響正式站詞庫。',libraryTitle:'讓概念更容易理解。',librarySub:'英文術語保留原文，釋義隨你選擇的語言切換。',search:'搜尋英文術語或釋義…',all:'全部課程',savedOnly:'只看收藏',allWords:'全部術語',save:'收藏術語',unsave:'取消收藏',empty:'找不到術語。試試其他關鍵字或課程。',found:'條術語',quizTitle:'把理解，變成記憶。',quizSub:'選出英文術語對應的釋義。每輪 8 題，完成後查看成績。',begin:'開始 8 題練習',back:'返回上一頁',question:'題',select:'選擇正確的釋義',right:'答對了',wrong:'再看一下這個概念',next:'下一題',finish:'查看成績',complete:'本輪練習完成',score:'答對',again:'再練一輪',review:'瀏覽術語複習',quizNote:'釋義和選項隨語言切換；題目與作答進度保留。',aboutTitle:'幫助不同母語的學生，讀懂同一堂課。',aboutIntro:'CourseLex AI 是一個圍繞大學課程的專業術語學習專案。它把英文術語與學習者熟悉的語言連結起來，再透過練習鞏固理解。',problem:'我們想解決的問題',problemText:'學生可能認識一個詞的日常用法，卻不理解它在傳播、政策或研究中的專業含義。查詞、整理和複習分散在不同工具裡，也讓學習更費力。',experience:'你現在可以體驗',features:['依四個課程主題瀏覽術語，搜尋和收藏學習卡。','在簡體中文、繁體中文、韓語和日語之間切換。','完成四選一練習，獲得即時回饋並查看本輪成績。'],nextTitle:'下一步，一起完善',nextText:'希望與老師及學生合作，驗證課程術語的準確性、改進多語言釋義，並測試練習是否幫助理解。正式產品已有課件整理方向；此站僅展示獨立的學習體驗。',attribution:'製作 @王大葱',version:'教師展示 · 版本 1.0',local:'本地收藏',total:'已完成練習',rounds:'輪',footer:'面向不同母語的學習者',courseNames:['新媒體政策與法規','傳播學基礎','網際網路傳播','傳播與新媒體研究方法']},
ko:{home:'홈',library:'용어 모음',practice:'연습',about:'프로젝트 소개',badge:'교수님 시연 · 다국어 학습',headline:'전문 용어의 이해,<br>익숙한 언어에서 시작하세요.',intro:'수업 속 영어 개념을 이해하고, 기억하고, 활용할 수 있는 지식으로. 다양한 모국어를 가진 학습자를 위해 만들었습니다.',start:'체험 시작',explore:'용어 살펴보기',sample:'학습 카드 예시',meaning:'모국어 풀이',context:'수업 속 맥락',remember:'이해에서 기억으로',courses:'과목 주제',terms:'예시 용어',languages:'학습 언어',choose:'과목을 선택해 시작하세요',chooseSub:'커뮤니케이션과 뉴미디어 분야의 예시 용어 모음입니다.',open:'과목 살펴보기 →',workflow:'강의 자료에서 나만의 용어 모음으로',workflowSub:'제품 방향: 강의 자료의 용어를 정리하고 풀이를 확인한 뒤 과목별로 연습합니다. 이 시연은 미리 준비된 예시를 사용하며 파일 업로드나 AI 호출은 하지 않습니다.',steps:['용어 정리','개념 이해','연습과 복습'],demo:'독립 시연 사이트입니다. 32개 예시 용어를 사용하며 즐겨찾기와 연습 기록은 이 브라우저에만 저장됩니다. 기존 사이트의 데이터에는 영향을 주지 않습니다.',libraryTitle:'개념을 더 쉽게 이해하세요.',librarySub:'영어 용어는 원문 그대로, 풀이는 선택한 언어로 표시됩니다.',search:'영어 용어 또는 풀이 검색…',all:'모든 과목',savedOnly:'즐겨찾기만',allWords:'모든 용어',save:'즐겨찾기 추가',unsave:'즐겨찾기 해제',empty:'검색 결과가 없습니다. 다른 검색어나 과목을 선택해 보세요.',found:'개 용어',quizTitle:'이해를 기억으로 바꾸세요.',quizSub:'영어 용어에 맞는 풀이를 고르세요. 한 회에 8문제이며 마지막에 점수를 확인할 수 있습니다.',begin:'8문제 연습 시작',back:'이전 화면으로',question:'문제',select:'올바른 풀이를 선택하세요',right:'정답입니다',wrong:'이 개념을 다시 확인해 보세요',next:'다음 문제',finish:'결과 보기',complete:'연습을 완료했습니다',score:'정답',again:'다시 연습하기',review:'용어 보며 복습하기',quizNote:'언어를 바꾸면 풀이와 선택지가 바뀌며 문제와 답변 진행 상황은 유지됩니다.',aboutTitle:'모국어가 달라도, 같은 수업을 이해할 수 있도록.',aboutIntro:'CourseLex AI는 대학 수업의 전문 용어를 학습하는 프로젝트입니다. 영어 용어를 학습자에게 익숙한 언어와 연결하고, 연습을 통해 이해를 다집니다.',problem:'해결하고 싶은 문제',problemText:'학생이 단어의 일상적인 뜻을 알아도 커뮤니케이션, 정책, 연구 분야의 전문적인 의미는 낯설 수 있습니다. 검색, 정리, 복습이 여러 도구에 흩어져 있으면 학습도 어려워집니다.',experience:'지금 체험할 수 있는 기능',features:['네 가지 과목 주제별 용어 탐색, 검색, 학습 카드 즐겨찾기.','간체 중국어, 번체 중국어, 한국어, 일본어 전환.','객관식 연습, 즉각적인 피드백, 회차별 점수 확인.'],nextTitle:'함께 발전시킬 다음 단계',nextText:'교수님과 학생들의 도움으로 과목 용어의 정확성을 검토하고 다국어 풀이를 개선하며 연습의 학습 효과를 확인하고 싶습니다. 실제 제품은 강의 자료 정리 기능을 지향하며, 이 사이트는 독립적인 학습 경험을 시연합니다.',attribution:'제작 @王大葱',version:'교수님 시연 · 버전 1.0',local:'즐겨찾기',total:'완료한 연습',rounds:'회',footer:'다양한 모국어를 가진 학습자를 위해',courseNames:['뉴미디어 정책과 규제','커뮤니케이션 기초','인터넷 커뮤니케이션','커뮤니케이션과 뉴미디어 연구 방법']},
ja:{home:'ホーム',library:'用語集',practice:'練習',about:'プロジェクト紹介',badge:'教員向けデモ · 多言語学習',headline:'専門用語の理解は、<br>あなたの言語から。',intro:'授業の英語の概念を、理解し、覚え、使える知識へ。さまざまな母語を持つ学習者のために設計しました。',start:'体験を始める',explore:'用語を見る',sample:'学習カードの例',meaning:'母語での解説',context:'授業での文脈',remember:'理解から記憶へ',courses:'科目のテーマ',terms:'サンプル用語',languages:'学習言語',choose:'科目を選んで始めましょう',chooseSub:'コミュニケーションとニューメディア分野のサンプル用語集です。',open:'科目を見る →',workflow:'授業資料から、自分の用語集へ',workflowSub:'製品の方向性：授業資料の用語を整理し、解説を確認して科目ごとに練習します。このデモは準備済みのサンプルを使用し、ファイルのアップロードや AI の呼び出しは行いません。',steps:['用語を整理','概念を理解','練習で定着'],demo:'独立したデモサイトです。32語のサンプルを使用し、お気に入りと練習記録はこのブラウザだけに保存します。正式サイトのデータには影響しません。',libraryTitle:'概念を、もっとわかりやすく。',librarySub:'英語の用語は原文のまま、解説は選択した言語で表示します。',search:'英語の用語・解説を検索…',all:'すべての科目',savedOnly:'お気に入りのみ',allWords:'すべての用語',save:'お気に入りに追加',unsave:'お気に入りを解除',empty:'用語が見つかりません。別のキーワードや科目をお試しください。',found:'語',quizTitle:'理解を、記憶に変えましょう。',quizSub:'英語の用語に合う解説を選びます。1回8問で、終了後に得点を確認できます。',begin:'8問の練習を始める',back:'前の画面に戻る',question:'問',select:'正しい解説を選んでください',right:'正解です',wrong:'この概念をもう一度確認しましょう',next:'次の問題',finish:'結果を見る',complete:'練習が完了しました',score:'正解',again:'もう一度練習',review:'用語を見て復習',quizNote:'言語を切り替えると解説と選択肢が変わり、問題と回答の進行状況は保持されます。',aboutTitle:'母語が違っても、同じ授業を理解できるように。',aboutIntro:'CourseLex AI は大学の授業に沿って専門用語を学ぶプロジェクトです。英語の用語を学習者になじみのある言語と結びつけ、練習を通じて理解を深めます。',problem:'解決したい課題',problemText:'単語の日常的な意味を知っていても、コミュニケーション、政策、研究分野での専門的な意味は難しいことがあります。検索、整理、復習が複数のツールに分かれていると、学習の負担も増えます。',experience:'今、体験できること',features:['4つの科目テーマで用語を閲覧・検索し、学習カードをお気に入りに保存。','簡体字中国語、繁体字中国語、韓国語、日本語の切り替え。','四択の練習、すぐにわかるフィードバック、各回の得点表示。'],nextTitle:'一緒に育てる、次のステップ',nextText:'先生や学生と協力して、科目用語の正確さを確認し、多言語の解説を改善し、練習が理解に役立つかを検証したいと考えています。正式製品は授業資料の整理機能を目指しており、このサイトは独立した学習体験を展示します。',attribution:'制作 @王大葱',version:'教員向けデモ · バージョン 1.0',local:'お気に入り',total:'完了した練習',rounds:'回',footer:'さまざまな母語を持つ学習者のために',courseNames:['ニューメディア政策と規制','コミュニケーションの基礎','インターネット・コミュニケーション','コミュニケーションとニューメディアの研究方法']}
};
// Curated demonstration material. Translations are examples for instructor review.
const ROWS=[
[0,'Privacy','隐私：个人控制其私人生活与信息被他人获取的范围。','隱私：個人控制其私人生活與資訊被他人取得的範圍。','프라이버시: 사생활과 개인정보가 타인에게 공개되는 범위를 통제하는 것.','プライバシー：私生活や個人情報が他者に知られる範囲をコントロールすること。','Privacy affects how platforms collect and share personal information.'],
[0,'Informed consent','知情同意：在了解用途、风险和选择后，自愿作出同意。','知情同意：在了解用途、風險和選擇後，自願作出同意。','사전 동의: 목적, 위험, 선택지를 이해한 뒤 자발적으로 동의하는 것.','インフォームド・コンセント：目的、リスク、選択肢を理解したうえで自発的に同意すること。','Participants should give informed consent before a study begins.'],
[0,'Copyright','著作权：法律赋予原创作品创作者的复制、传播等权利。','著作權：法律賦予原創作品創作者的重製、傳播等權利。','저작권: 창작물의 복제와 배포 등에 대해 창작자에게 부여되는 법적 권리.','著作権：創作物の複製や公衆への伝達などについて創作者に認められる法的権利。','Copyright protects the original expression in a photograph.'],
[0,'Defamation','诽谤：传播损害他人声誉的虚假事实陈述。','誹謗：傳播損害他人聲譽的虛假事實陳述。','명예훼손: 다른 사람의 평판을 해치는 허위 사실을 전달하는 행위.','名誉毀損：他者の評判を損なう虚偽の事実を伝える行為。','The lecture examines a defamation claim involving a false online report.'],
[0,'Data minimization','数据最小化：仅收集实现特定目的所必要的个人数据。','資料最小化：僅蒐集實現特定目的所必要的個人資料。','데이터 최소화: 특정 목적에 필요한 개인정보만 수집하는 원칙.','データ最小化：特定の目的に必要な個人データだけを収集する原則。','Data minimization limits unnecessary collection of user information.'],
[0,'Freedom of expression','表达自由：表达意见、寻求和传播信息的自由。','表達自由：表達意見、尋求和傳播資訊的自由。','표현의 자유: 의견을 표현하고 정보를 찾고 전달할 자유.','表現の自由：意見を表し、情報を求め、伝える自由。','Media policy considers freedom of expression alongside other rights.'],
[0,'Platform governance','平台治理：管理数字平台行为、内容与责任的规则和机制。','平台治理：管理數位平台行為、內容與責任的規則和機制。','플랫폼 거버넌스: 디지털 플랫폼의 행동, 콘텐츠, 책임을 관리하는 규칙과 체계.','プラットフォーム・ガバナンス：デジタル基盤の行動、コンテンツ、責任を管理する規則と仕組み。','Platform governance includes rules for content moderation.'],
[0,'Public interest','公共利益：与社会整体福祉有关的利益。','公共利益：與社會整體福祉有關的利益。','공익: 사회 전체의 복지와 관련된 이익.','公共の利益：社会全体の福祉に関わる利益。','A journalist may weigh privacy against the public interest.'],
[1,'Agenda-setting','议程设置：媒体通过突出某些议题，影响公众关注什么。','議程設定：媒體透過凸顯某些議題，影響公眾關注什麼。','의제 설정: 미디어가 특정 이슈를 강조하여 대중의 관심 의제에 영향을 주는 과정.','アジェンダ設定：メディアが特定の問題を強調し、人々が何に注目するかに影響を与えること。','Agenda-setting helps explain why some issues become public priorities.'],
[1,'Framing','框架建构：通过选择与强调信息，塑造议题的理解方式。','框架建構：透過選擇與強調資訊，形塑議題的理解方式。','프레이밍: 정보의 선택과 강조를 통해 이슈를 이해하는 방식을 형성하는 것.','フレーミング：情報の選択や強調によって、問題の捉え方を形づくること。','Framing can present the same event as a risk or an opportunity.'],
[1,'Gatekeeping','把关：决定哪些信息进入传播渠道的筛选过程。','把關：決定哪些資訊進入傳播管道的篩選過程。','게이트키핑: 어떤 정보가 전달 경로에 들어갈지 결정하는 선별 과정.','ゲートキーピング：どの情報を伝達経路に載せるかを決める選別過程。','Editors perform gatekeeping when selecting stories.'],
[1,'Encoding','编码：把想法转化为可传播的符号或信息。','編碼：把想法轉化為可傳播的符號或訊息。','부호화: 생각을 전달할 수 있는 기호나 메시지로 바꾸는 과정.','エンコーディング：考えを伝達可能な記号やメッセージに変える過程。','Encoding turns an idea into a spoken or written message.'],
[1,'Decoding','解码：接收者解释信息中的符号与意义。','解碼：接收者解讀訊息中的符號與意義。','해독: 수신자가 메시지의 기호와 의미를 해석하는 과정.','デコーディング：受け手がメッセージの記号や意味を解釈する過程。','Decoding depends partly on the audience’s cultural background.'],
[1,'Feedback','反馈：接收者对信息作出的回应。','回饋：接收者對訊息作出的回應。','피드백: 수신자가 메시지에 대해 보내는 반응.','フィードバック：受け手がメッセージに対して返す反応。','A question from the audience provides feedback to the speaker.'],
[1,'Noise','噪声：干扰信息传递或理解的因素。','雜訊：干擾訊息傳遞或理解的因素。','잡음: 메시지 전달이나 이해를 방해하는 요인.','ノイズ：メッセージの伝達や理解を妨げる要因。','Technical problems can create noise during a video call.'],
[1,'Uses and gratifications','使用与满足：从受众需求出发解释人们为何选择与使用媒体。','使用與滿足：從閱聽人需求出發解釋人們為何選擇與使用媒體。','이용과 충족: 이용자의 욕구를 바탕으로 미디어 선택과 이용을 설명하는 접근.','利用と満足：受け手のニーズから、メディアを選び利用する理由を説明する考え方。','Uses and gratifications examines the needs behind media choices.'],
[2,'Algorithmic curation','算法筛选：利用算法选择、排序和推荐内容。','演算法篩選：利用演算法選擇、排序和推薦內容。','알고리즘 큐레이션: 알고리즘으로 콘텐츠를 선택하고 순서를 정해 추천하는 것.','アルゴリズムによる選別：アルゴリズムでコンテンツを選び、並べ、推薦すること。','Algorithmic curation shapes a personalized news feed.'],
[2,'Echo chamber','回音室：相似观点不断重复，异质观点较少进入的信息环境。','回音室：相似觀點不斷重複，異質觀點較少進入的資訊環境。','에코 챔버: 비슷한 견해가 반복되고 다른 견해는 적게 유입되는 정보 환경.','エコーチェンバー：似た意見が繰り返され、異なる意見が入りにくい情報環境。','An echo chamber can reinforce existing opinions.'],
[2,'Filter bubble','过滤气泡：个性化筛选使个人较少接触不同信息的现象。','過濾氣泡：個人化篩選使個人較少接觸不同資訊的現象。','필터 버블: 개인화된 정보 선별로 다양한 정보에 덜 노출되는 현상.','フィルターバブル：個人向けの情報選別により、多様な情報に触れにくくなる現象。','A filter bubble may narrow the range of recommended content.'],
[2,'Digital divide','数字鸿沟：不同群体在数字技术获取、技能或受益方面的差距。','數位落差：不同群體在數位技術取得、技能或受益方面的差距。','디지털 격차: 집단 간 디지털 기술 접근, 활용 능력, 혜택의 차이.','デジタル・ディバイド：集団間のデジタル技術へのアクセス、技能、恩恵の格差。','The digital divide includes unequal access to reliable internet.'],
[2,'Network effect','网络效应：用户增加会改变产品对其他用户的价值。','網路效應：使用者增加會改變產品對其他使用者的價值。','네트워크 효과: 이용자 수의 변화가 다른 이용자에게 제공되는 제품의 가치에 영향을 주는 현상.','ネットワーク効果：利用者数の変化が、他の利用者にとっての製品の価値に影響する現象。','A messaging service can gain value through a network effect.'],
[2,'Participatory culture','参与式文化：成员积极创作、分享并参与集体活动的文化。','參與式文化：成員積極創作、分享並參與集體活動的文化。','참여 문화: 구성원이 적극적으로 창작하고 공유하며 집단 활동에 참여하는 문화.','参加型文化：参加者が積極的に創作・共有し、共同の活動に関わる文化。','Fan communities often illustrate participatory culture.'],
[2,'Virality','病毒式传播：内容经用户分享快速扩散的特征。','病毒式傳播：內容經使用者分享快速擴散的特徵。','바이럴 확산: 이용자들의 공유를 통해 콘텐츠가 빠르게 퍼지는 특성.','バイラル拡散：利用者による共有を通じてコンテンツが急速に広がる性質。','Virality can bring a short video to a large audience.'],
[2,'Affordance','可供性：技术与使用者关系中形成的行动可能性。','可供性：技術與使用者關係中形成的行動可能性。','어포던스: 기술과 이용자의 관계에서 형성되는 행동의 가능성.','アフォーダンス：技術と利用者の関係の中で生まれる行為の可能性。','A share button offers an affordance for distributing content.'],
[3,'Hypothesis','假设：可以通过研究检验的预测性陈述。','假設：可以透過研究檢驗的預測性陳述。','가설: 연구를 통해 검증할 수 있는 예측적 진술.','仮説：研究によって検証できる予測的な記述。','The study tests a hypothesis about media use and trust.'],
[3,'Independent variable','自变量：用于解释或预测结果，或在实验中被操纵的变量。','自變項：用於解釋或預測結果，或在實驗中被操弄的變項。','독립변수: 결과를 설명하거나 예측하기 위해 사용되거나 실험에서 조작되는 변수.','独立変数：結果を説明・予測するために用いる、または実験で操作する変数。','Message format is the independent variable in this experiment.'],
[3,'Dependent variable','因变量：研究中被测量和解释的结果变量。','依變項：研究中被測量和解釋的結果變項。','종속변수: 연구에서 측정하고 설명하려는 결과 변수.','従属変数：研究で測定し、説明しようとする結果の変数。','Recall accuracy is the dependent variable in this study.'],
[3,'Validity','效度：测量或研究结论是否准确反映所要研究的对象。','效度：測量或研究結論是否準確反映所要研究的對象。','타당도: 측정이나 연구 결론이 연구하려는 대상을 얼마나 정확히 반영하는지.','妥当性：測定や研究の結論が、調べたい対象をどれほど正確に捉えているか。','Validity asks whether a scale measures the intended concept.'],
[3,'Reliability','信度：测量结果在一致条件下的稳定性或一致性。','信度：測量結果在一致條件下的穩定性或一致性。','신뢰도: 동일한 조건에서 측정 결과가 얼마나 안정적이고 일관적인지.','信頼性：同じ条件での測定結果の安定性や一貫性。','Reliability concerns the consistency of measurement.'],
[3,'Sampling','抽样：从总体中选择部分对象进行研究的过程。','抽樣：從母群體中選擇部分對象進行研究的過程。','표집: 모집단에서 연구할 일부 대상을 선택하는 과정.','サンプリング：母集団から研究対象の一部を選ぶ過程。','Sampling determines which participants enter a survey.'],
[3,'Correlation','相关：两个变量随彼此变化的统计关系，并不直接证明因果。','相關：兩個變項隨彼此變化的統計關係，並不直接證明因果。','상관: 두 변수가 함께 변화하는 통계적 관계로, 인과관계를 직접 증명하지는 않음.','相関：2つの変数がともに変化する統計的な関係で、因果関係を直接示すものではない。','A correlation between two measures does not establish causation.'],
[3,'Content analysis','内容分析：用系统规则对传播内容进行编码和分析的方法。','內容分析：用系統規則對傳播內容進行編碼和分析的方法。','내용 분석: 체계적인 규칙으로 커뮤니케이션 내용을 코딩하고 분석하는 방법.','内容分析：体系的な規則でコミュニケーションの内容を分類し、分析する方法。','Content analysis can compare themes across news articles.']
];
const locales=Object.keys(COPY),codes=['COM5103','COM5101','COM5501','COM5104'];
const terms=ROWS.map((r,id)=>({id,course:r[0],en:r[1],meanings:Object.fromEntries(locales.map((l,i)=>[l,r[i+2]])),example:r[6]}));
const KEY='sv-teacher-demo-v1';
function read(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
const stored=read();let lang=locales.includes(stored.lang)?stored.lang:'zh-Hans',saved=new Set(Array.isArray(stored.saved)?stored.saved.filter(id=>Number.isInteger(id)):[]),rounds=Number.isInteger(stored.rounds)?stored.rounds:0;
let filter=-1,search='',onlySaved=false,quiz=null;
const app=document.getElementById('app'),language=document.getElementById('language');
function persist(){try{localStorage.setItem(KEY,JSON.stringify({lang,saved:[...saved],rounds}))}catch{}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function t(){return COPY[lang]}
function route(){return location.hash.split('?')[0].slice(1)||'home'}
function courseOptions(){return `<option value="-1">${t().all}</option>`+codes.map((code,i)=>`<option value="${i}" ${filter===i?'selected':''}>${code} · ${t().courseNames[i]}</option>`).join('')}
function shell(){const c=t();document.documentElement.lang=lang;document.title=`CourseLex AI · ${c.version}`;language.value=lang;document.getElementById('nav').innerHTML=['home','library','practice','about'].map(v=>`<a href="#${v}" ${route()===v?'class="active" aria-current="page"':''}>${c[v]}</a>`).join('');document.getElementById('footer').innerHTML=`<span>${c.attribution} · ${c.footer}</span><span>${c.version}</span>`}
function home(){const c=t(),sample=terms[8];app.innerHTML=`<section class="hero"><div><div class="eyebrow"><span class="dot"></span>${c.badge}</div><h1>${c.headline}</h1><p>${c.intro}</p><div class="actions"><a class="button primary" href="#practice">${c.start} ↗</a><a class="button" href="#library">${c.explore}</a></div><div class="stats"><div><strong>4</strong>${c.courses}</div><div><strong>32</strong>${c.terms}</div><div><strong>4</strong>${c.languages}</div></div></div><div class="preview"><div class="sheet"><div class="minirow"><span>${c.sample}</span><span>COM5101 · 01</span></div><div class="word">${sample.en}</div><div class="tag">${c.meaning}</div><p class="definition">${sample.meanings[lang]}</p><div class="line"><div class="eyebrow">${c.context}</div><div class="context">${sample.example}</div></div><div class="minirow line"><span>${c.remember}</span><span>↗</span></div></div></div></section><section><div class="section-top"><div><h2>${c.choose}</h2><p>${c.chooseSub}</p></div><span class="tag">${c.version}</span></div><div class="grid">${codes.map((code,i)=>`<article class="course"><div class="num">0${i+1} / ${code}</div><h3>${c.courseNames[i]}</h3><p>8 ${c.found}</p><a href="#library?course=${i}">${c.open}</a></article>`).join('')}</div></section><section class="process"><div><h3>${c.workflow}</h3><p>${c.workflowSub}</p></div><div class="steps">${c.steps.map((s,i)=>`<span>0${i+1} &nbsp;${s}</span>`).join('<span aria-hidden="true">→</span>')}</div></section><div class="notice">${c.demo}</div>`}
function library(){const c=t();app.innerHTML=`<div class="eyebrow"><span class="dot"></span>${c.library}</div><h1>${c.libraryTitle}</h1><p>${c.librarySub}</p><div class="toolbar"><input id="search" type="search" aria-label="${c.search}" placeholder="${c.search}" value="${esc(search)}"><select id="course" aria-label="${c.courses}">${courseOptions()}</select><button id="saved-filter" aria-pressed="${onlySaved}" class="${onlySaved?'primary':''}">${onlySaved?c.allWords:c.savedOnly}</button></div><div id="wordlist"></div>`;wordlist();document.getElementById('search').addEventListener('input',e=>{search=e.target.value;wordlist()});document.getElementById('course').addEventListener('change',e=>{filter=+e.target.value;wordlist()});document.getElementById('saved-filter').onclick=()=>{onlySaved=!onlySaved;library()}}
function wordlist(){const c=t(),q=search.toLocaleLowerCase().trim(),found=availableTerms().filter(w=>(filter<0||w.course===filter)&&(!onlySaved||saved.has(w.id))&&(!weekFilter||w.week===weekFilter)&&(!q||(w.en+' '+w.meanings[lang]).toLocaleLowerCase().includes(q)));document.getElementById('wordlist').innerHTML=`<div class="count">${found.length} ${c.found} · ${c.local} ${saved.size}</div><div class="words">${found.map(w=>`<article class="term"><button class="save ${saved.has(w.id)?'saved':''}" data-save="${w.id}" aria-label="${saved.has(w.id)?c.unsave:c.save}" aria-pressed="${saved.has(w.id)}">${saved.has(w.id)?'★':'☆'}</button><span class="tag">${codes[w.course]}</span><h3>${esc(w.en)}</h3><p class="translation">${esc(w.meanings[lang])}</p><div class="context">${esc(w.example)}</div></article>`).join('')}</div>${found.length?'':`<div class="empty">${c.empty}</div>`}`;document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=+b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);persist();wordlist()})}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startQuiz(){const pool=availableTerms().filter(w=>(filter<0||w.course===filter)&&(!weekFilter||w.week===weekFilter));if(!pool.length||pool.some(w=>demoDistractors(w).length<3)){showMessage(t().notEnough);return}quiz={questions:shuffle(pool).slice(0,8).map(w=>({id:w.id,options:shuffle([w.id,...demoDistractors(w)]),answer:null})),index:0,score:0,done:false};practice()}
function practice(){const c=t();if(!quiz){app.innerHTML=`<section class="quiz"><div class="eyebrow"><span class="dot"></span>${c.practice}</div><h1>${c.quizTitle}</h1><p>${c.quizSub}</p><div class="toolbar"><select id="quiz-course" aria-label="${c.courses}">${courseOptions()}</select></div><button class="primary" id="begin">${c.begin} →</button><div class="notice">${c.quizNote}</div><p>${c.total}: ${rounds} ${c.rounds}</p></section>`;document.getElementById('quiz-course').onchange=e=>{filter=+e.target.value};document.getElementById('begin').onclick=startQuiz;return}if(quiz.done){app.innerHTML=`<section class="quiz result"><div class="eyebrow">${c.practice}</div><h1>${c.complete}</h1><strong>${quiz.score} / ${quiz.questions.length}</strong><p>${c.score} · ${c.total} ${rounds} ${c.rounds}</p><div class="actions" style="justify-content:center"><button class="primary" id="again">${c.again}</button><a class="button" href="#library">${c.review}</a></div><div class="notice">${c.demo}</div></section>`;document.getElementById('again').onclick=startQuiz;return}const q=quiz.questions[quiz.index],w=terms[q.id],answered=q.answer!==null;app.innerHTML=`<section class="quiz"><div class="quizhead"><button id="back">← ${c.back}</button><span>${quiz.index+1} / ${quiz.questions.length} · ${c.question}</span></div><div class="progress"><span style="width:${(quiz.index+(answered?1:0))/quiz.questions.length*100}%"></span></div><div class="question"><span class="tag">${codes[w.course]} · ${c.courseNames[w.course]}</span><h1>${esc(w.en)}</h1><p>${c.select}</p><div class="options">${q.options.map((id,i)=>`<button data-answer="${id}" ${answered?'disabled':''} class="${answered&&id===q.id?'correct':answered&&id===q.answer?'wrong':''}"><span>${String.fromCharCode(65+i)}</span>${esc(terms[id].meanings[lang])}</button>`).join('')}</div>${answered?`<div class="feedback" role="status"><b>${q.answer===q.id?'✓ '+c.right:c.wrong}</b><p>${esc(w.meanings[lang])}</p><div class="context">${esc(w.example)}</div><button class="primary" id="next">${quiz.index===quiz.questions.length-1?c.finish:c.next} →</button></div>`:''}</div><div class="notice">${c.quizNote}</div></section>`;document.getElementById('back').onclick=()=>{location.hash='home'};document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(q.answer!==null)return;q.answer=+b.dataset.answer;if(q.answer===q.id)quiz.score++;learning[q.id]=q.answer===q.id?'known':'unknown';saveLearning();practice()});if(answered)document.getElementById('next').onclick=()=>{if(quiz.index===quiz.questions.length-1){quiz.done=true;rounds++;persist()}else quiz.index++;practice()}}
function about(){const c=t();app.innerHTML=`<section class="about"><div class="eyebrow"><span class="dot"></span>${c.about}</div><h1>${c.aboutTitle}</h1><p>${c.aboutIntro}</p><article><h2>${c.problem}</h2><p>${c.problemText}</p></article><article><h2>${c.experience}</h2><ul>${c.features.map(x=>`<li>${x}</li>`).join('')}</ul></article><article><h2>${c.nextTitle}</h2><p>${c.nextText}</p><a class="button primary" href="#practice">${c.start} →</a></article><div class="notice">${c.demo}</div></section>`}
function render(){shell();({home,library,practice,about}[route()]||home)()}
language.addEventListener('change',()=>{lang=language.value;persist();render()});window.addEventListener('hashchange',()=>{const m=location.hash.match(/course=([0-3])/);if(m){filter=+m[1];search='';onlySaved=false}render();window.scrollTo(0,0)});const initial=location.hash.match(/course=([0-3])/);if(initial)filter=+initial[1];render();
