'use strict';
// Keep in-app navigation local. Returning never sends the user out of CourseLex AI.
let viewTrail=[],activeHash=location.hash||'#home',pendingReturn=null;
const cloneState=value=>value?JSON.parse(JSON.stringify(value)):null;
function captureView(hash=activeHash){return {hash,filter,weekFilter,search,onlySaved,quiz:cloneState(quiz),recognition:cloneState(recognitionSession),uploadCourse,uploadWeek,scrollY:window.scrollY}}
function restoreView(view){filter=view.filter;weekFilter=view.weekFilter;search=view.search;onlySaved=view.onlySaved;quiz=cloneState(view.quiz);recognitionSession=cloneState(view.recognition);uploadCourse=view.uploadCourse;uploadWeek=view.uploadWeek}
function fallbackView(){const r=route();let hash='#home';if(r==='library'&&filter>=0&&weekFilter)hash='#weeks?course='+filter;if(['practice','recognition'].includes(r)&&filter>=0)hash='#library?course='+filter+(weekFilter?'&week='+weekFilter:'');return {...captureView(hash),quiz:null,recognition:null,scrollY:0}}
function goBack(){const view=viewTrail.pop()||fallbackView();if(view.hash===activeHash){restoreView(view);render();window.scrollTo(0,view.scrollY||0);return}pendingReturn=view;location.hash=view.hash}
function handleRouteChange(){const nextHash=location.hash||'#home';if(pendingReturn){const view=pendingReturn;pendingReturn=null;restoreView(view);activeHash=nextHash;render();window.scrollTo(0,view.scrollY||0);return}viewTrail.push(captureView());activeHash=nextHash;quiz=null;recognitionSession=null;const courseMatch=location.hash.match(/course=([0-3])/),weekMatch=location.hash.match(/week=(\d+)/);if(courseMatch){filter=+courseMatch[1];search='';onlySaved=false;if(!weekMatch)weekFilter=0}render();window.scrollTo(0,0)}
function wireBack(){if(route()==='home')return;let controls=[...app.querySelectorAll('button,a')].filter(el=>el.textContent.trim()==='← '+t().back);if(!controls.length){const control=document.createElement('button');control.className='back-control';control.textContent='← '+t().back;const section=app.querySelector('.quiz,.about');(section||app).prepend(control);controls=[control]}for(const control of controls){if(control.tagName==='A')control.href=(viewTrail.at(-1)||fallbackView()).hash;control.onclick=e=>{e.preventDefault();goBack()}}}
function equalModes(){const r=route(),c=t();if(r==='home'){const actions=app.querySelector('.hero .actions'),choice=actions.querySelector('[href="#practice"]'),recognition=actions.querySelector('[href="#recognition"]');if(choice&&recognition&&!choice.parentElement.classList.contains('mode-picker')){choice.textContent=c.choice;recognition.textContent=c.recognition;const pair=document.createElement('div');pair.className='mode-picker';actions.prepend(pair);pair.append(choice,recognition)}}if(r==='practice'&&!quiz){const choice=document.getElementById('begin');const alternative=app.querySelector('[href="#recognition"]');if(alternative)alternative.remove();if(choice)choice.textContent=({ 'zh-Hans':'开始练习','zh-Hant':'開始練習',ko:'연습 시작',ja:'練習を始める' })[lang]}if(r==='recognition'&&!recognitionSession){const begin=document.getElementById('recognition-start');if(begin)begin.textContent=({ 'zh-Hans':'开始学习','zh-Hant':'開始學習',ko:'학습 시작',ja:'学習を始める' })[lang]}if(['library','known','unknown'].includes(r)){const toolbar=app.querySelector('.toolbar'),choice=toolbar.querySelector('[href="#practice"]'),recognition=toolbar.querySelector('[href="#recognition"]');if(choice&&recognition&&!choice.parentElement.classList.contains('mode-picker')){const pair=document.createElement('div');pair.className='mode-picker';choice.before(pair);pair.append(choice,recognition)}}app.querySelectorAll('.mode-picker>a,.mode-picker>button').forEach(el=>el.className='button mode-button');app.querySelectorAll('#recognition-known,#recognition-unknown,#recognition-yes,#recognition-no').forEach(el=>el.className='button decision-button')}
const featureRender=render,featurePractice=practice,featureRecognition=recognition,featureHome=home,featureLibrary=library,featureStartQuiz=startQuiz;
render=function(){featureRender();equalModes();wireBack()};
practice=function(){featurePractice();equalModes();wireBack()};
recognition=function(){featureRecognition();equalModes();wireBack();const begin=document.getElementById('recognition-start');if(begin){const start=begin.onclick;begin.onclick=()=>{const before=captureView();start();if(recognitionSession)viewTrail.push(before)}}};
home=function(){featureHome();equalModes()};
library=function(){featureLibrary();equalModes();wireBack()};
startQuiz=function(){const before=captureView();featureStartQuiz();if(quiz)viewTrail.push(before)};
const initialWeek=location.hash.match(/week=(\d+)/);if(initialWeek)weekFilter=+initialWeek[1];
window.addEventListener('hashchange',handleRouteChange);
render();
